name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 1. Lay code tu Repo
        uses: actions/checkout@v4

      - name: 2. Cai dat Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 3. Chay Build va Kiem tra Coverage
        # Su dung verify de kich hoat jacoco-check va bao cao
        run: chmod +x mvnw && ./mvnw clean verify -ntp

      - name: 4. Luu file .jar (Artifact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: MathUtils-Jar-${{ matrix.os }}
          path: target/*.jar

      - name: 5. Luu bao cao JaCoCo (Artifact)
        # Su dung if: always() de luon co bao cao ngay ca khi build fail do thieu coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Jacoco-Report-${{ matrix.os }}
          path: target/site/jacoco/